<a href="https://colab.research.google.com/github/Sebas080602/C8280-/blob/main/Actividad_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ALUMNO: SEBASTIAN ANTONIO SALDAÑA RODRIGUEZ

In [ ]:
from __future__ import division
import time
import numpy as np

tam_vec = 1000

def lista_python():
    t1 = time.time()
    X = range(tam_vec)
    Y = range(tam_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

def matriz_numpy():
    t1 = time.time()
    X = np.arange(tam_vec)
    Y = np.arange(tam_vec)
    Z = X + Y
    return time.time() - t1

tiempo_lista_python = lista_python()
tiempo_matriz_numpy = matriz_numpy()

print("Tiempo de ejecución utilizando lista en Python:", tiempo_lista_python)
print("Tiempo de ejecución utilizando matriz NumPy:", tiempo_matriz_numpy)


Tiempo de ejecución utilizando lista en Python: 0.0002110004425048828
Tiempo de ejecución utilizando matriz NumPy: 0.008327007293701172


In [ ]:
import numpy as np

# Creamos una matriz de rango 1
a = np.array([0, 1, 2])
print (type(a))

# Imprimimos la dimension de la matriz
print (a.shape)
print (a[0])
print (a[1])
print (a[2])

# Cambiamos un elemento de un array
a[0] = 5
print (a)

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [ ]:
# Creamos una matriz de rango 2
b = np.array([[0,1,2],[3,4,5]])
print (b.shape)
print (b)
print (b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [ ]:
print ( b.shape)
print ( b[0, 0], b[0, 1], b[1, 0])

(2, 3)
0 1 3


In [ ]:
# Creamos una matriz 3x3 de todos ceros
a = np.zeros((3,3))
print (a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Creamos una matriz 2x2 de todos 1
b = np.ones((2,2))
print (b)

[[1. 1.]
 [1. 1.]]


In [ ]:
# Creamos una matriz 3x3 constantes
c = np.full((3,3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# Creamos una matriz 3x3 con valores aleatorios
d = np.random.random((3,3))
print (d)

[[0.46867429 0.48162935 0.55255933]
 [0.12222796 0.1767319  0.31947032]
 [0.94905873 0.23141582 0.37820354]]


In [ ]:
# Creamos una matriz identidad 3x3
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Convertir una lista en una matriz
f = np.array([2, 3, 1,0])
print(f)

[2 3 1 0]


In [ ]:
# arange() crea matrices con valores que se incrementan regularmente
g = np.arange(0, 10, 2)  # Crea una matriz con valores de 0 a 8, incrementando de 2 en 2
print(g)

[0 2 4 6 8]


In [ ]:
# Mezcla de tuplas y listas
h = np.array([(1, 2, 3), [4, 5, 6]])
print(h)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Crear una matriz de rango con tipo de datos flotante
i = np.arange(1, 8, dtype=np.float64)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


In [ ]:
# linspace() crea matrices con un número específico de elementos que están espaciados por igual entre los valores inicial y final especificados
j = np.linspace(0, 1, 5)  # Crea una matriz con 5 elementos espaciados por igual entre 0 y 1
print(j)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Numpy escoge el tipo de datos
x = np.array([0, 1])
y = np.array([2.0, 3.0])

# Fuerza un tipo de datos en particular
z = np.array([5, 6], dtype=np.int64)
print (x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [ ]:
import numpy as np

# Configuración de la semilla aleatoria para reproducibilidad
np.random.seed(0)

x1 = np.random.randint(10, size=6)  # Matriz 1D
x2 = np.random.randint(10, size=(5, 4))  # Matriz 2D
x3 = np.random.randint(10, size=(2, 4, 5))  # Matriz 3D

print("Matriz 1D:")
print("Dimensión:", x1.ndim)
print("Forma:", x1.shape)
print("Tamaño:", x1.size)
print("Tipo de datos:", x1.dtype)
print("Tamaño de cada elemento (en bytes):", x1.itemsize)
print("Tamaño total de la matriz (en bytes):", x1.nbytes)
print()

print("Matriz 2D:")
print("Dimensión:", x2.ndim)
print("Forma:", x2.shape)
print("Tamaño:", x2.size)
print("Tipo de datos:", x2.dtype)
print("Tamaño de cada elemento (en bytes):", x2.itemsize)
print("Tamaño total de la matriz (en bytes):", x2.nbytes)
print()

print("Matriz 3D:")
print("Dimensión:", x3.ndim)
print("Forma:", x3.shape)
print("Tamaño:", x3.size)
print("Tipo de datos:", x3.dtype)
print("Tamaño de cada elemento (en bytes):", x3.itemsize)
print("Tamaño total de la matriz (en bytes):", x3.nbytes)


Matriz 1D:
Dimensión: 1
Forma: (6,)
Tamaño: 6
Tipo de datos: int64
Tamaño de cada elemento (en bytes): 8
Tamaño total de la matriz (en bytes): 48

Matriz 2D:
Dimensión: 2
Forma: (5, 4)
Tamaño: 20
Tipo de datos: int64
Tamaño de cada elemento (en bytes): 8
Tamaño total de la matriz (en bytes): 160

Matriz 3D:
Dimensión: 3
Forma: (2, 4, 5)
Tamaño: 40
Tipo de datos: int64
Tamaño de cada elemento (en bytes): 8
Tamaño total de la matriz (en bytes): 320


In [ ]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
print(x)

[[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]]


In [ ]:
print ("x['a'].shape: ",x['a'].shape)
print ("x['a'].dtype: ", x['a'].dtype)

print ("x['b'].shape: ", x['b'].shape)
print ("x['b'].dtype: ", x['b'].dtype)

x['a'].shape:  (3, 3)
x['a'].dtype:  int32
x['b'].shape:  (3, 3, 3, 3)
x['b'].dtype:  float64


In [ ]:
x = np.array([5, 6, 7, 8, 9])
x[1:7:2]

array([6, 8])

In [ ]:
print (x[-2:5])
print (x[-1:1:-1])

[8 9]
[9 8 7]


In [ ]:
x[4:]

array([9])

In [ ]:
import numpy as np

# Recorte con tupla de selección incompleta
z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Recorte con tupla de selección incompleta:")
print(z[:2])  # Selecciona las dos primeras filas de la matriz
print(z[:, 1])  # Selecciona la segunda columna de la matriz
print(z[:2, 1:])  # Selecciona las dos primeras filas y las columnas desde la segunda hasta el final


Recorte con tupla de selección incompleta:
[[1 2 3]
 [4 5 6]]
[2 5 8]
[[2 3]
 [5 6]]


In [ ]:
import numpy as np
# OTRO EJEMPLO
# Ejemplo de recorte básico
x = np.array([5, 6, 7, 8, 9])
print("Recorte básico:")
print(x[1:7:2])  # Selecciona los elementos desde el índice 1 hasta el índice 7 (no inclusivo) con un paso de 2
print()

# Recorte con índices negativos
print("Recorte con índices negativos:")
print(x[-2:5])  # Selecciona los elementos desde el índice -2 hasta el índice 5
print(x[-1:1:-1])  # Selecciona los elementos desde el índice -1 hasta el índice 1 en orden inverso
print()

# Recorte con valores predeterminados
print("Recorte con valores predeterminados:")
print(x[4:])  # Selecciona los elementos desde el índice 4 hasta el final
print()

# Recorte en matrices multidimensionales
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Recorte en matrices multidimensionales:")
print(y[0:2, 1:3])  # Selecciona los elementos en las filas 0 y 1, y en las columnas 1 y 2


Recorte básico:
[6 8]

Recorte con índices negativos:
[8 9]
[9 8 7]

Recorte con valores predeterminados:
[9]

Recorte en matrices multidimensionales:
[[2 3]
 [5 6]]


In [ ]:
print(x)

[5 6 7 8 9]


In [ ]:
x[...,0]

array(5)

In [ ]:
'''
Ejercicio
Crea una matriz de rango 2 con dimension (3, 4)

Usa el recorte para extraer la submatriz que consta de las primeras 2 filas y las columnas 1 y 2.

Una parte de una matriz es solo una vista de los mismos datos, comprueba quecualquier modificación modificará la matriz original.
'''
import numpy as np

# Crear una matriz de rango 2 con dimensiones (3, 4)
matriz = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("Matriz original:")
print(matriz)
print()

# Recorte para extraer la submatriz de las primeras 2 filas y las columnas 1 y 2
submatriz = matriz[0:2, 0:2]

print("Submatriz extraída:")
print(submatriz)
print()

# Modificar la submatriz
submatriz[0, 0] = 99

print("Submatriz modificada:")
print(submatriz)
print()

# Verificar que la matriz original también se modifique
print("Matriz original después de modificar la submatriz:")
print(matriz)


Matriz original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Submatriz extraída:
[[1 2]
 [5 6]]

Submatriz modificada:
[[99  2]
 [ 5  6]]

Matriz original después de modificar la submatriz:
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Creamos una matriz de rango 2 array con dimensión (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
fila_r1 = a[1, :]    # Vista de rango 1 de la segunda fila de a
fila_r2 = a[1:2, :]  # Vista de rango 2 de la segunda fila de a
fila_r3 = a[[1], :]  # Vista de ranfo 2 de la segunda fila de a
print (fila_r1, fila_r1.shape)
print (fila_r2, fila_r2.shape)
print (fila_r3, fila_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
a = [[1, 2], [3, 4]]
result = [a[0][0], a[1][1]]
print(result)


[1, 4]


In [ ]:
a = [[1, 2], [3, 4]]
result = [a[0][1], a[0][1]]
print(result)


[2, 2]


In [ ]:
np.random.seed(0)
x2 = np.random.randint(10, size=(5, 4))
x2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6],
       [7, 7, 8, 1]])

In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[5 0]
 [7 9]]


In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  0]
 [ 7  9]]


In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  0]
 [ 7  9]]


In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  0]
 [ 7  9]]


In [ ]:
print(x2)

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]
 [ 8  8  1  6]
 [ 7  7  8  1]]


In [ ]:
x4 = np.arange(1, 10).reshape((3, 3))
print(x4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

x5 = np.array([1, 2, 3])
print("Vector original:", x5)

# Vector fila utilizando reshape
vector_fila_reshape = x5.reshape((1, x5.shape[0]))
print("Vector fila utilizando reshape:", vector_fila_reshape)

# Vector fila utilizando newaxis
vector_fila_newaxis = x5[np.newaxis, :]
print("Vector fila utilizando newaxis:", vector_fila_newaxis)

# Vector columna utilizando reshape
vector_columna_reshape = x5.reshape((x5.shape[0], 1))
print("Vector columna utilizando reshape:", vector_columna_reshape)

# Vector columna utilizando newaxis
vector_columna_newaxis = x5[:, np.newaxis]
print("Vector columna utilizando newaxis:", vector_columna_newaxis)


Vector original: [1 2 3]
Vector fila utilizando reshape: [[1 2 3]]
Vector fila utilizando newaxis: [[1 2 3]]
Vector columna utilizando reshape: [[1]
 [2]
 [3]]
Vector columna utilizando newaxis: [[1]
 [2]
 [3]]


In [ ]:
x = np.array([4, 5, 6])
y = np.array([7, 8, 9])
np.concatenate([x, y])

array([4, 5, 6, 7, 8, 9])

In [ ]:
# concatenacion de dos o mas matrices
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 4  5  6  7  8  9 99 99 99]


In [ ]:
# concatendo una matriz dos veces
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np

x = np.array([0, 1, 2])
grid = np.array([[3, 4, 5],
                 [6, 5, 4]])

# Unir matrices verticalmente
matriz_vertical = np.vstack((x, grid))
print("Unir matrices verticalmente:")
print(matriz_vertical)

# Unir matrices horizontalmente
y = np.array([[23],
              [23]])
matriz_horizontal = np.hstack((grid, y))
print("Unir matrices horizontalmente:")
print(matriz_horizontal)


Unir matrices verticalmente:
[[0 1 2]
 [3 4 5]
 [6 5 4]]
Unir matrices horizontalmente:
[[ 3  4  5 23]
 [ 6  5  4 23]]


In [ ]:
x = [1, 2, 3, 44, 95, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [44 95] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
grid1, grid2 = np.vsplit(grid, [2])
print(grid1)
print(grid2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
grid3, grid4 = np.hsplit(grid,[2])
print(grid3)
print(grid4)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [ ]:
# Accedemos a tres elementos diferentes
[x[1], x[5], x[2]]

[92, 20, 14]

In [ ]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

# Accedemos a tres elementos diferentes
indices = [1, 5, 2]
resultado = x[indices]
print(resultado)


[51 92 14 71 60 20 82 86 74 74]
[92 20 14]


In [ ]:
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

indices_row = np.array([0, 2])
indices_col = np.array([1, 2])

resultado = X[indices_row, indices_col]
print(resultado)


[2 9]


In [ ]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
fila = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[fila, col]

array([ 2,  5, 11])

In [ ]:
indices_row = np.array([[0],
                       [2]])
indices_col = np.array([1, 3])

resultado = X[indices_row, indices_col]
print(resultado)



[[ 1  3]
 [ 9 11]]


In [ ]:
indices_row = np.array([0, 2])
indices_col = np.array([1, 3])

resultado = X[indices_row[:, np.newaxis], indices_col]
print(resultado)


[[ 1  3]
 [ 9 11]]


In [ ]:
indices_fancy = np.array([0, 2])
indices_simple = 1

resultado = X[indices_fancy, indices_simple]
print(resultado)


[1 9]


In [ ]:
indices_fancy = np.array([0, 2])
indices_recorte = slice(1, 3)

resultado = X[indices_fancy, indices_recorte]
print(resultado)

[[ 1  2]
 [ 9 10]]


In [ ]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [ ]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
indices = [0, 1, 2]

np.add.at(x, indices, 1)

print(x)


[2 3 4 4 5]


In [ ]:
L = np.random.random(100)
sum(L)

47.03631196196963

In [ ]:
np.sum(L)

47.03631196196964

In [ ]:
matriz_grande = np.random.rand(1000000)
%timeit sum(matriz_grande)
%timeit np.sum(matriz_grande)

103 ms ± 17.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
263 µs ± 9.89 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
# Otras funciones min y max
min(matriz_grande), max(matriz_grande)

(7.071203171893359e-07, 0.9999997207656334)

In [ ]:
%timeit min(matriz_grande)
%timeit np.min(matriz_grande)

72.4 ms ± 5.81 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
192 µs ± 27 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
data = np.random.normal(size=(15, 15))
np.mean(data)

0.044126718568646986

In [ ]:
data.mean()

0.044126718568646986

In [ ]:
M = np.random.random((5, 6))
print(M)

[[0.78911301 0.63111867 0.7285163  0.66979703 0.17088322 0.13881003]
 [0.00935403 0.63751707 0.76420221 0.1876222  0.95137218 0.44469986]
 [0.47577551 0.43077223 0.49532871 0.58341548 0.27654054 0.96025749]
 [0.12685672 0.38686572 0.29660634 0.99907694 0.00377931 0.82984241]
 [0.75816216 0.01685189 0.23811077 0.28054238 0.63922302 0.31781681]]


In [ ]:
M.sum()

14.238830244406318

In [ ]:
M.sum(axis= 0)

array([2.15926144, 2.10312558, 2.52276433, 2.72045403, 2.04179827,
       2.69142659])

In [ ]:
data = np.random.normal(size=(5, 10, 15))
data.sum(axis=0).shape

(10, 15)

In [ ]:
data.sum(axis=(0, 2)).shape

(10,)

In [ ]:
data.sum()

-40.96575138792459

In [ ]:
a = np.array([0, 1, 2])
b = np.array([2, 6, 1])
a + b

array([2, 7, 3])

In [ ]:
a + 5

array([5, 6, 7])

In [ ]:
A = np.arange(16).reshape(4, 4)
b = np.arange(4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
A + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [ ]:
import numpy as np

a = np.array([0, 1, 2])
b = np.array([2, 6, 1])

result1 = a + b
print(result1)

result2 = a + 5
print(result2)

A = np.arange(16).reshape(4, 4)
b = np.arange(4)

result3 = A + b
print(result3)

# Broadcasting en dos matrices
C = np.array([[1, 2, 3]])
D = np.array([[4], [5], [6]])

result4 = C + D
print(result4)


[2 7 3]
[5 6 7]
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
J = np.arange(0, 40, 10)
J.shape

(4,)

In [ ]:
J = J[:, np.newaxis]  # agregamos un nuevo eje ->  matriz 2D
J.shape


(4, 1)

In [ ]:
J

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
J + 3

array([[ 3],
       [13],
       [23],
       [33]])

In [ ]:
a1 = np.array([1, 2, 3, 4])
b1 = np.array([4, 3, 2, 1])
a1 < b1

array([ True,  True, False, False])

In [ ]:
np.all(a1 < b1)

False

In [ ]:
np.any(a1 < b1)

True

In [ ]:
if np.all(a1 < b1):
    print(" Todos los elementos en a1 son menores que los elementos en b1 ")
elif np.any(a1 < b1):
    print("Algunos elementos en a1 son menores que los elementos de b1")
else:
    print("Todos los elementos en b1 son menores que los elementos de a1")

Algunos elementos en a1 son menores que los elementos de b1


In [ ]:
import numpy as np

a = np.array([0, 1, 2])
b = np.array([2, 6, 1])

result1 = a + b
print(result1)

result2 = a + 5
print(result2)

A = np.arange(16).reshape(4, 4)
b = np.arange(4)

result3 = A + b
print(result3)

# Broadcasting en dos matrices
C = np.array([[1, 2, 3]])
D = np.array([[4], [5], [6]])

result4 = C + D
print(result4)


[2 7 3]
[5 6 7]
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
def pulso(t, posicion, altura, ancho):
    return altura * ((t >= posicion) & (t <= (posicion + ancho)))


In [ ]:
t = np.linspace(0, 10, 100)
posicion = 2
altura = 5
ancho = 3

resultado = pulso(t, posicion, altura, ancho)
print(resultado)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
k = np.array([1, 3, -1, 5, 7, -1])
mask = (k < 0)
mask

array([False, False,  True, False, False,  True])

In [ ]:
# Un ejemplo bidimensional
rng = np.random.RandomState(0)
z1 = rng.randint(10, size=(3, 4))
z1

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [ ]:
k = np.array([1, 3, -1, 5, 7, -1])
mask = (k < 0)
print(mask)


[False False  True False False  True]


In [ ]:
rng = np.random.RandomState(0)
z1 = rng.randint(10, size=(3, 4))
print(z1)


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [ ]:
z1 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

mask = np.array([[True, False, True, False],
                 [False, True, False, True],
                 [True, False, True, False]])

masked_sum = np.sum(z1 * mask)
print(masked_sum)


38


In [ ]:
z1 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

mask = np.array([[True, False, True, False],
                 [False, True, False, True],
                 [True, False, True, False]])

masked_values = z1[mask]
print(masked_values)


[ 1  3  6  8  9 11]


In [ ]:
z1 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

mask = np.array([[True, False, True, False],
                 [False, True, False, True],
                 [True, False, True, False]])

sum_of_masked_values = np.sum(z1[mask])
print(sum_of_masked_values)


38
